name: Downloadable Archive Ready
on: 
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Archive Release
      uses: vimtor/action-zip@v1.1
      with:
        files: FlowMax-Q.zip
        recursive: false
        dest: FlowMax-Q.zip
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "FlowMax-Q.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
